# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Jonathan Muller (aka Bhaal22)

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf

